### PR TITLE
fix SyntaxError: Unexpected token )

### PR DESCRIPTION
**Pull request by dilrajahdan**

### CODE REVIEW

**Comment by dilrajahdan** [comment]
This comma was crashing when starting `ember s`.

**Comment by ivanvanderbyl** [comment]
What version of node are you running?

**Comment by dilrajahdan** [comment]
Node v7.10.1

**Comment by dilrajahdan** [comment]
Sorry, i think that was a red herring. 

I'll close this and create an issue instead.

**Pull request closed without merging**
